import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { GaitSession } from './sessionDb';
import { fmtDate } from './utils';

function fmtDuration(secs: number): string {
  const m = Math.floor(secs / 60).toString().padStart(2, '0');
  const s = (secs % 60).toString().padStart(2, '0');
  return `${m}m ${s}s`;
}

function drawHeader(doc: jsPDF, session: GaitSession, page: number, total: number): void {
  const W = doc.internal.pageSize.getWidth();
  const H = 18;

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, H, 'F');

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(87, 241, 219);
  doc.text('GAITPRECISION', 10, 12);

  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Clinical Gait Analysis Report', 10, 16.5);

  doc.text(
    `${session.id}  ·  ${fmtDate(session.date)}  ·  Score ${session.score}/100  ·  ${session.status}`,
    W - 10, 10.5,
    { align: 'right' },
  );
  doc.text(
    `${session.label}  ·  Duration ${fmtDuration(session.duration)}  ·  Page ${page} of ${total}`,
    W - 10, 15.5,
    { align: 'right' },
  );
}

function drawFooter(doc: jsPDF): void {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const FH = 9;

  doc.setFillColor(15, 23, 42);
  doc.rect(0, H - FH, W, FH, 'F');

  doc.setFontSize(5.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Generated by GaitPrecision  ·  ${new Date().toISOString().split('T')[0]}  ·  All biometric data processed on-device  ·  Not a substitute for clinical judgement`,
    W / 2,
    H - 3,
    { align: 'center' },
  );
}

/**
 * Captures `captureEl` with html2canvas, then assembles a multi-page A4 PDF
 * with a branded header and footer on every page. Triggers a browser download.
 */
export async function exportSessionPdf(
  captureEl: HTMLElement,
  session: GaitSession,
): Promise<void> {
  // Capture the element at 2× for retina-quality output.
  const canvas = await html2canvas(captureEl, {
    scale: 2,
    useCORS: true,
    backgroundColor: '#0f172a',
    logging: false,
  });

  const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W      = doc.internal.pageSize.getWidth();   // 210 mm
  const H      = doc.internal.pageSize.getHeight();  // 297 mm

  const MARGIN    = 10;   // mm — left/right/bottom gap
  const HEADER_H  = 18;   // mm
  const FOOTER_H  =  9;   // mm
  const SLOT_H    = H - HEADER_H - MARGIN - FOOTER_H; // usable content height per page

  const contentW    = W - MARGIN * 2;          // 190 mm
  const pxPerMm     = canvas.width / contentW; // canvas pixels per mm
  const totalImgH   = canvas.height / pxPerMm; // full image height in mm
  const totalPages  = Math.max(1, Math.ceil(totalImgH / SLOT_H));

  for (let p = 0; p < totalPages; p++) {
    if (p > 0) doc.addPage();

    drawHeader(doc, session, p + 1, totalPages);
    drawFooter(doc);

    // Slice the canvas vertically for this page.
    const srcYPx = Math.round(p * SLOT_H * pxPerMm);
    const srcHPx = Math.min(
      Math.round(SLOT_H * pxPerMm),
      canvas.height - srcYPx,
    );
    if (srcHPx <= 0) break;

    const slice     = document.createElement('canvas');
    slice.width     = canvas.width;
    slice.height    = srcHPx;
    slice.getContext('2d')!.drawImage(
      canvas,
      0, srcYPx,      canvas.width, srcHPx,
      0, 0,           canvas.width, srcHPx,
    );

    doc.addImage(
      slice.toDataURL('image/png'),
      'PNG',
      MARGIN,
      HEADER_H + MARGIN,
      contentW,
      srcHPx / pxPerMm,
    );
  }

  doc.save(`GaitPrecision_${session.id}.pdf`);
}
