import jsPDF from 'jspdf';
import type { GaitSession } from './sessionDb';
import type { UserProfile, AgeGroup } from './userProfile';
import { BENCHMARKS, AGE_GROUP_LABELS } from './userProfile';
import { pickExercises } from './exercises';

// ── Brand colours (print-safe) ──────────────────────────────────────────────
type RGB = [number, number, number];
const TEAL: RGB    = [32,  163, 143];
const DARK: RGB    = [30,  41,  59 ];
const MID: RGB     = [100, 116, 139];
const LIGHT: RGB   = [226, 232, 240];
const WHITE: RGB   = [255, 255, 255];
const AMBER: RGB   = [217, 119,  6 ];
const RED: RGB     = [220,  38, 38 ];
const OFFWHITE: RGB = [248, 250, 252];

// ── Page geometry (US Letter) ────────────────────────────────────────────────
const PAGE_W = 215.9;
const PAGE_H = 279.4;
const ML = 20;
const MR = 20;
const CW = PAGE_W - ML - MR; // 175.9 mm usable width
const FOOTER_H = 20;         // reserved at bottom

// ── Helpers ──────────────────────────────────────────────────────────────────
function fmtDurationLong(secs: number): string {
  const m = Math.floor(secs / 60);
  const s = secs % 60;
  if (m === 0) return `${s} sec`;
  if (s === 0) return `${m} min`;
  return `${m} min ${s} sec`;
}

function fmtDateLong(ts: number): string {
  return new Date(ts).toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
  });
}

function wellnessLabel(score: number): { label: string; stars: number } {
  if (score >= 85) return { label: 'Excellent',        stars: 5 };
  if (score >= 70) return { label: 'Good',             stars: 4 };
  if (score >= 55) return { label: 'Fair',             stars: 3 };
  if (score >= 40) return { label: 'Needs Work',       stars: 2 };
  return             { label: 'Needs Attention',  stars: 1 };
}

function fallRiskInfo(score: number, asymmetry: number): { text: string; color: RGB } {
  if (score < 60 || asymmetry > 20) return { text: 'Elevated', color: RED   };
  if (score < 70 || asymmetry > 12) return { text: 'Moderate', color: AMBER };
  return                                    { text: 'Low',      color: TEAL  };
}

function balanceInfo(asymmetry: number): { text: string; color: RGB } {
  if (asymmetry <= 10) return { text: 'Balanced',         color: TEAL  };
  if (asymmetry <= 20) return { text: 'Slight Imbalance', color: AMBER };
  return                      { text: 'Imbalanced',       color: RED   };
}

function scoreColor(stars: number): RGB {
  if (stars >= 4) return TEAL;
  if (stars === 3) return AMBER;
  return RED;
}

// Draw 5 small square "star" indicators
function drawStars(doc: jsPDF, x: number, y: number, count: number) {
  const SZ = 4;
  const GAP = 1.5;
  for (let i = 0; i < 5; i++) {
    doc.setFillColor(...(i < count ? TEAL : LIGHT));
    doc.rect(x + i * (SZ + GAP), y, SZ, SZ, 'F');
  }
}

// Draw a horizontal progress bar
function drawBar(doc: jsPDF, x: number, y: number, w: number, ratio: number, color: RGB) {
  const H = 3.5;
  doc.setFillColor(...LIGHT);
  doc.rect(x, y, w, H, 'F');
  doc.setFillColor(...color);
  doc.rect(x, y, Math.min(w, w * ratio), H, 'F');
}

// Draw footer on current page
function drawFooter(doc: jsPDF) {
  const fy = PAGE_H - FOOTER_H + 4;
  doc.setDrawColor(...LIGHT);
  doc.setLineWidth(0.3);
  doc.line(ML, fy - 2, PAGE_W - MR, fy - 2);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...MID);
  doc.text(
    'Generated by GaitPrecision  ·  Share this report with your doctor or physical therapist.',
    ML, fy + 2,
  );
  doc.text(
    'All analysis runs entirely on your device. No personal data is sent to any server.',
    ML, fy + 6.5,
  );
}

// ── Main export ───────────────────────────────────────────────────────────────
export function generateSessionPDF(
  session: GaitSession,
  profile: UserProfile | null,
  ageGroup: AgeGroup | null,
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'letter', orientation: 'portrait' });

  // Derived values
  const asymmetry = session.kneeAngles.left.length
    ? Math.abs((session.kneeAngles.left.at(-1) ?? 0) - (session.kneeAngles.right.at(-1) ?? 0))
    : 0;
  const cadence      = session.stride?.cadence ?? 0;
  const { label: scoreLabel, stars } = wellnessLabel(session.score);
  const fallRisk     = fallRiskInfo(session.score, asymmetry);
  const balance      = balanceInfo(asymmetry);
  const exercises    = pickExercises(session);
  const bench        = ageGroup ? BENCHMARKS[ageGroup] : null;
  const ageGroupLbl  = ageGroup ? AGE_GROUP_LABELS[ageGroup] : null;

  // ── Pagination helpers ────────────────────────────────────────────────────
  let y = 0;

  function addPage() {
    drawFooter(doc);
    doc.addPage();
    y = 18;
  }

  function ensureSpace(needed: number) {
    if (y + needed > PAGE_H - FOOTER_H) addPage();
  }

  // ── HEADER STRIP ─────────────────────────────────────────────────────────
  const HDR_H = 27;
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, HDR_H, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...WHITE);
  doc.text('GaitPrecision', ML, 11);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(200, 240, 235);
  doc.text('Walking Health Report', ML, 20);

  doc.setFontSize(8.5);
  doc.setTextColor(...WHITE);
  doc.text(
    new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
    PAGE_W - MR, 20, { align: 'right' },
  );

  y = HDR_H + 11;

  // ── PATIENT / SESSION ROW ─────────────────────────────────────────────────
  if (profile?.name) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...DARK);
    doc.text(profile.name, ML, y);

    if (profile.age) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...MID);
      doc.text(`Age ${profile.age}`, ML + 65, y);
    }
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MID);
  doc.text(
    `Session: ${fmtDateLong(session.date)}  ·  ${fmtDurationLong(session.duration)}`,
    PAGE_W - MR, y, { align: 'right' },
  );

  y += 9;

  // ── SEPARATOR ────────────────────────────────────────────────────────────
  doc.setDrawColor(...LIGHT);
  doc.setLineWidth(0.3);
  doc.line(ML, y, PAGE_W - MR, y);
  y += 9;

  // ── SCORE BLOCK ──────────────────────────────────────────────────────────
  const SC = scoreColor(stars);

  // Large score number
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(54);
  doc.setTextColor(...DARK);
  doc.text(String(session.score), ML, y + 19);

  // "/100" suffix
  doc.setFontSize(16);
  doc.setTextColor(...MID);
  doc.text('/100', ML + 28, y + 19);

  // Label
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...SC);
  doc.text(scoreLabel.toUpperCase(), ML + 57, y + 11);

  // Stars
  drawStars(doc, ML + 57, y + 14.5, stars);

  // Sub-label
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...MID);
  doc.text('Walking Score  (0 – 100)', ML + 57, y + 28);

  y += 38;

  // ── SEPARATOR ────────────────────────────────────────────────────────────
  doc.setDrawColor(...LIGHT);
  doc.line(ML, y, PAGE_W - MR, y);
  y += 9;

  // ── METRICS CARDS ────────────────────────────────────────────────────────
  const hasStance = !!(session.stride?.left?.stancePercent && session.stride?.right?.stancePercent);
  interface MetricCard { label: string; value: string; sub?: string; color: RGB }
  const cards: MetricCard[] = [
    { label: 'Balance',   value: balance.text,       color: balance.color },
    { label: 'Fall Risk', value: fallRisk.text,       color: fallRisk.color },
    ...(cadence > 0
      ? [{ label: 'Steps / Min', value: String(cadence), sub: 'steps per minute', color: TEAL }]
      : []),
    ...(hasStance
      ? [{
          label: 'Time on Each Leg',
          value: `Left ${session.stride!.left.stancePercent}%`,
          sub:   `Right ${session.stride!.right.stancePercent}%`,
          color: DARK,
        }]
      : [{ label: 'Duration', value: fmtDurationLong(session.duration), color: DARK }]),
  ];

  const CARD_H   = 28;
  const CARD_GAP = 4;
  const CARD_W   = (CW - CARD_GAP * (cards.length - 1)) / cards.length;

  cards.forEach((card, i) => {
    const cx = ML + i * (CARD_W + CARD_GAP);
    doc.setFillColor(...OFFWHITE);
    doc.setDrawColor(...LIGHT);
    doc.setLineWidth(0.3);
    doc.rect(cx, y, CARD_W, CARD_H, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...MID);
    doc.text(card.label.toUpperCase(), cx + 4, y + 6);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...card.color);
    doc.text(card.value, cx + 4, y + 16);

    if (card.sub) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...MID);
      doc.text(card.sub, cx + 4, y + 23);
    }
  });

  y += CARD_H + 10;

  // ── AGE COMPARISON ────────────────────────────────────────────────────────
  if (bench && ageGroupLbl) {
    ensureSpace(48);

    doc.setDrawColor(...LIGHT);
    doc.line(ML, y, PAGE_W - MR, y);
    y += 9;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...DARK);
    doc.text('How You Compare', ML, y);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...MID);
    doc.text(ageGroupLbl, PAGE_W - MR, y, { align: 'right' });
    y += 8;

    const compRows = [
      { label: 'Walking Score',   user: session.score, avg: bench.score,   unit: '/ 100' },
      ...(cadence > 0 ? [{ label: 'Steps per Minute', user: cadence, avg: bench.cadence, unit: 'spm' }] : []),
    ];

    compRows.forEach((row) => {
      const ratio  = row.avg > 0 ? row.user / row.avg : 1;
      const isGreat = ratio >= 1.05;
      const isGood  = ratio >= 0.9;
      const clr: RGB = isGreat ? TEAL : isGood ? AMBER : RED;
      const status   = isGreat ? 'Above Average' : isGood ? 'On Track' : 'Below Average';

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      doc.text(row.label, ML, y + 4);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...clr);
      doc.text(`${row.user} ${row.unit}`, ML + 60, y + 4);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...clr);
      doc.text(status, ML + 100, y + 4);

      doc.setTextColor(...MID);
      doc.text(`Average: ${row.avg} ${row.unit}`, PAGE_W - MR, y + 4, { align: 'right' });

      y += 6;
      drawBar(doc, ML, y, CW, Math.min(1.1, ratio), clr);
      y += 9;
    });

    y += 4;
  }

  // ── EXERCISES ────────────────────────────────────────────────────────────
  ensureSpace(30);
  doc.setDrawColor(...LIGHT);
  doc.line(ML, y, PAGE_W - MR, y);
  y += 9;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.text('Recommended Exercises', ML, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...MID);
  doc.text(
    'Always consult your doctor before starting a new exercise program.',
    PAGE_W - MR, y, { align: 'right' },
  );
  y += 12;

  exercises.forEach((ex, idx) => {
    // Estimate space needed for this exercise card
    const whyLines  = doc.splitTextToSize(ex.why, CW - 10) as string[];
    const stepLines = ex.steps.map(s => doc.splitTextToSize(s, CW - 16) as string[]);
    const stepH     = stepLines.reduce((sum, l) => sum + l.length * 4.8 + 3, 0);
    const needed    = 11 + whyLines.length * 4.8 + 5 + stepH + 10;

    ensureSpace(needed + 6);

    const exStart = y;

    // Number badge
    doc.setFillColor(...TEAL);
    doc.rect(ML, y, 7, 7, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...WHITE);
    doc.text(String(idx + 1), ML + 3.5, y + 5.2, { align: 'center' });

    // Exercise name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12.5);
    doc.setTextColor(...DARK);
    doc.text(ex.name, ML + 10, y + 5.8);

    // Difficulty badge
    const badgeClr: RGB = ex.difficulty === 'Easy' ? TEAL : AMBER;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...badgeClr);
    doc.text(ex.difficulty.toUpperCase(), PAGE_W - MR, y + 5.8, { align: 'right' });

    y += 11;

    // Why (italic)
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9.5);
    doc.setTextColor(...MID);
    doc.text(whyLines, ML + 2, y);
    y += whyLines.length * 4.8 + 5;

    // Steps
    stepLines.forEach((lines, si) => {
      // Step number indicator
      doc.setFillColor(...TEAL);
      doc.rect(ML + 2, y - 0.5, 5, 5, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(...WHITE);
      doc.text(String(si + 1), ML + 4.5, y + 3, { align: 'center' });

      // Step text
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      doc.text(lines, ML + 10, y + 3.5);
      y += lines.length * 4.8 + 3;
    });

    y += 2;

    // Frequency row
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...TEAL);
    doc.text('Frequency:', ML + 2, y);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK);
    doc.text(ex.frequency, ML + 28, y);
    y += 10;

    // Divider between exercises (not after last)
    if (idx < exercises.length - 1) {
      doc.setDrawColor(...LIGHT);
      doc.setLineWidth(0.2);
      doc.line(ML, y, PAGE_W - MR, y);
      y += 6;
    }
  });

  // ── FOOTER (last page) ───────────────────────────────────────────────────
  drawFooter(doc);

  // ── SAVE ─────────────────────────────────────────────────────────────────
  const dateStr  = new Date(session.date).toISOString().slice(0, 10);
  const namePart = profile?.name
    ? profile.name.replace(/\s+/g, '_').toLowerCase() + '_'
    : '';
  doc.save(`GaitPrecision_${namePart}${dateStr}.pdf`);
}
